<a href="https://colab.research.google.com/github/Sanjay227001/MachineLearning_projects/blob/main/Creditcard_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('/content/sample_data/creditcard.csv')

In [ ]:
df.head(5)

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62    0.0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69    0.0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66    0.0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50    0.0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [ ]:
df.tail(5)

            Time        V1        V2  ...       V28  Amount  Class
210008  137803.0 -1.571064 -2.758091  ...  0.236764   18.00    0.0
210009  137803.0 -0.018165  0.079155  ...  0.263440   39.99    0.0
210010  137803.0 -0.960193  0.854343  ...  0.041936   25.00    0.0
210011  137803.0  1.832529  0.279144  ... -0.040156   18.96    0.0
210012  137803.0  1.555740 -1.014458  ...       NaN     NaN    NaN

[5 rows x 31 columns]

In [ ]:
df.shape

(210013, 31)

In [ ]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.shape

(210012, 31)

In [ ]:
#legit and Fraud transaction
df['Class'].value_counts()

Class
0.0    209618
1.0       394
Name: count, dtype: int64

1 -> Fraud trans
0 -> Normal Trans

In [ ]:
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(209618, 31)
(394, 31)

In [ ]:
legit.Amount.describe()

count    209618.000000
mean         89.889280
std         248.067423
min           0.000000
25%           6.000000
50%          23.020000
75%          79.540000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     394.000000
mean      123.172970
std       256.841767
min         0.000000
25%         1.000000
50%        13.385000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transaction
df.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28     Amount
Class                                    ...
0.0    73757.442119 -0.075414 -0.010262  ...  0.000703  0.001457   89.88928
1.0    62970.449239 -5.564086  4.145138  ...  0.182273  0.060390  123.17297

[2 rows x 30 columns]

UNDER SAMPLING

In [ ]:
#no of fraud trans
legit_sample = legit.sample(n=394)

In [ ]:
#concat 2 dataframes
new_df = pd.concat([legit_sample,fraud], axis = 0)

In [ ]:
new_df.head(5)

          Time        V1        V2        V3  ...       V27       V28  Amount  Class
84030  60133.0  1.307200  0.284121 -0.227873  ... -0.027174  0.007633    1.98    0.0
80484  58507.0 -0.473397  0.884519  1.324162  ...  0.085915  0.160038    0.99    0.0
3341    2892.0  1.296215 -0.799544  0.935654  ...  0.047237  0.024567   29.95    0.0
48475  43662.0 -0.039838  0.686086  1.159587  ...  0.174583  0.221189    1.29    0.0
83958  60106.0 -1.620361 -0.842397  1.578834  ...  0.020353 -0.014849   35.05    0.0

[5 rows x 31 columns]

Equal sampling Size

In [ ]:
new_df['Class'].value_counts()

Class
0.0    394
1.0    394
Name: count, dtype: int64

Features and Targets

In [ ]:
x = new_df.drop(columns = 'Class', axis = 1)
y = new_df['Class']

In [ ]:
print(x)

            Time        V1        V2  ...       V27       V28  Amount
84030    60133.0  1.307200  0.284121  ... -0.027174  0.007633    1.98
80484    58507.0 -0.473397  0.884519  ...  0.085915  0.160038    0.99
3341      2892.0  1.296215 -0.799544  ...  0.047237  0.024567   29.95
48475    43662.0 -0.039838  0.686086  ...  0.174583  0.221189    1.29
83958    60106.0 -1.620361 -0.842397  ...  0.020353 -0.014849   35.05
...          ...       ...       ...  ...       ...       ...     ...
203700  134928.0  1.204934  3.238070  ...  0.491828  0.340847    0.00
204064  135095.0  0.232512  0.938944  ...  0.180859 -0.029315  345.00
204079  135102.0  1.862102 -0.124052  ... -0.019579  0.006155  108.51
204503  135314.0 -3.158990  1.765452  ... -0.235477  0.018129   84.28
208651  137211.0  0.630579  1.183631  ...  0.853792  0.356503   39.45

[788 rows x 30 columns]

In [ ]:
print(y)

84030     0.0
80484     0.0
3341      0.0
48475     0.0
83958     0.0
         ...
203700    1.0
204064    1.0
204079    1.0
204503    1.0
208651    1.0
Name: Class, Length: 788, dtype: float64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify = y, random_state = 2)

In [ ]:
print(x.shape, x_train.shape, x_test.shape)

(788, 30) (630, 30) (158, 30)

Logistic Regression

In [ ]:
#training the logistic regression model

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Evaluation

In [ ]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [ ]:
print(training_data_accuracy)

0.9587301587301588

In [ ]:
x_test_prediction = model.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [ ]:
print(testing_data_accuracy)

0.930379746835443